name: Test

on:
  push:
    branches: [ 'test' ]

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'test'

      - name: Install Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm clean-install

      - name: Install ncc
        run: npm --location=global install ncc --loglevel verbose

      - name: Check path
        run: |
          ls -al /usr/local/bin
          which ncc
          whereis ncc

      - name: Generate unified release files with ncc
        run: |
          ncc build src/terraform.js -o dist/terraform -m
          ncc build src/wrapper.js -o dist/wrapper -m

      - name: Push to Github test tag
        run: |
          git add dist/*
          git update-index --chmod=+x dist/wrapper/index.js
          git commit -m "Auto test build"
          git tag -fa -m "Update test tag" test
          git push -f --follow-tags

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]    

    steps:
      - uses: buzzy/scalr-terraform-cli@test
        with:
          terraform_version: '1.2.1'
          scalr_token: 'test-token'
          scalr_hostname: 'test.scalr.io'

      - name: Whereis
        run: whereis terraform

      - id: version
        name: Version
        run: terraform -v

      - name: Print output
        run: echo '${{ steps.version.outputs.stdout }}'